### ISSUE TITLE
[Deploy]部署StapxsQQLite | NPM node-jieba安装失败 | 未找到'./../assets/img/qq-face/gif'

### ISSUE THREAD

**Issue by Starry-Sky-World** [Stapxs/Stapxs-QQ-Lite-2.0#128]
### 错误来源

其他

### 描述错误

很好奇作者怎么安装&运行的

### 复现流程

按文档安装
实测Windows NodeJS（同Action环境版本）下无法正常安装&运行

### 截图

![image](https://github.com/user-attachments/assets/25f7d632-f8d6-47e9-b1d7-e20c52052c84)
![image](https://github.com/user-attachments/assets/2f00b13b-0a82-459b-940c-757f0d002a45)
![image](https://github.com/user-attachments/assets/2b4a0b23-571d-4bab-812d-bc325f0f9fd8)

### 更多

```log
root@DESKTOP-LCLD13C:/home/liuqinyu/project/Stapxs-QQ-Lite-2.0# yarn install
yarn install v1.22.22
info No lockfile found.
[1/4] Resolving packages...
warning css > source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
warning pinyin > nodejieba > @mapbox/node-pre-gyp > npmlog@5.0.1: This package is no longer supported.
warning pinyin > nodejieba > @mapbox/node-pre-gyp > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning pinyin > nodejieba > @mapbox/node-pre-gyp > npmlog > gauge@3.0.2: This package is no longer supported.
warning pinyin > nodejieba > @mapbox/node-pre-gyp > npmlog > are-we-there-yet@2.0.0: This package is no longer supported.
warning pinyin > nodejieba > @mapbox/node-pre-gyp > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning pinyin > nodejieba > @mapbox/node-pre-gyp > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning @vue/cli-plugin-babel > @vue/babel-preset-app > @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
warning @vue/cli-plugin-pwa > workbox-webpack-plugin@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-broadcast-update@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-background-sync@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-cacheable-response@6.6.1: workbox-background-sync@6.6.1
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-broadcast-update > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-background-sync > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-cacheable-response > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-navigation-preload@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-navigation-preload > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-expiration@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-expiration > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-precaching@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-precaching > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-google-analytics@6.6.1: It is not compatible with newer versions of GA starting with v4, as long as you are using GAv3 it should be ok, but the package is not longer being maintained
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-google-analytics > workbox-background-sync@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-google-analytics > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-recipes@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-recipes > workbox-cacheable-response@6.6.1: workbox-background-sync@6.6.1
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-recipes > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-recipes > workbox-expiration@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-recipes > workbox-precaching@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-range-requests@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-range-requests > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-streams@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-streams > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-sw@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-strategies@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-precaching > workbox-strategies@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-google-analytics > workbox-strategies@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-recipes > workbox-strategies@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-strategies > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-routing@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-precaching > workbox-routing@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-google-analytics > workbox-routing@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-recipes > workbox-routing@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-streams > workbox-routing@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-routing > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-window@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > workbox-window > workbox-core@6.6.1: this package has been deprecated
warning @vue/cli-plugin-pwa > workbox-webpack-plugin > workbox-build > @surma/rollup-plugin-off-main-thread > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
warning @vue/cli-plugin-typescript > fork-ts-checker-webpack-plugin > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @vue/cli-plugin-typescript > fork-ts-checker-webpack-plugin > memfs@3.6.0: this will be v4
warning @vue/cli-service > webpack-chain@6.5.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @vue/cli-service > webpack-dev-server > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning @vue/cli-service > @vue/component-compiler-utils > consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
warning @vue/cli-service > webpack-dev-server > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @vue/cli-service > cssnano > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning electron-devtools-installer > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning eslint > @humanwhocodes/config-array@0.5.0: Use @eslint/config-array instead
warning eslint > file-entry-cache > flat-cache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning eslint > @humanwhocodes/config-array > @humanwhocodes/object-schema@1.2.1: Use @eslint/object-schema instead
warning vue-cli-plugin-electron-builder > webpack-chain@6.5.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning vue-cli-plugin-electron-builder > electron-builder > app-builder-lib > electron-osx-sign@0.5.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
warning vue-cli-plugin-electron-builder > electron-builder > app-builder-lib > @electron/universal > asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
warning vue-cli-plugin-electron-builder > electron-builder > app-builder-lib > @electron/universal > asar > glob@7.2.3: Glob versions prior to v9 are no longer supported
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
warning pinyin@3.1.0: The engine "install-node" appears to be invalid.
[3/4] Linking dependencies...
warning " > raw-loader@4.0.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > ts-loader@8.2.0" has unmet peer dependency "webpack@*".
[4/4] Building fresh packages...
[-/4] ⠐ waiting...
[2/4] ⠐ nodejieba
[-/4] ⠐ waiting...
warning Error running install script for optional dependency: "/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@18.20.4 | linux | x64
node-pre-gyp info check checked for \"/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba/build/Release/nodejieba.node\" (not found)
node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-linux-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for nodejieba@2.5.2 and node@18.20.4 (node-v108 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-linux-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@18.20.4 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@18.20.4 | linux | x64
gyp info find Python using Python version 3.10.12 found at \"/usr/bin/python3\"

gyp http GET https://nodejs.org/download/release/v18.20.4/node-v18.20.4-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v18.20.4/node-v18.20.4-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v18.20.4/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v18.20.4/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args '/root/.nvm/versions/node/v18.20.4/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/root/.nvm/versions/node/v18.20.4/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/root/.cache/node-gyp/18.20.4/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/18.20.4',
gyp info spawn args '-Dnode_gyp_dir=/root/.nvm/versions/node/v18.20.4/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/18.20.4/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@18.20.4 | linux | x64
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/root/.nvm/versions/node/v18.20.4/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
gyp ERR! stack at which (/root/.nvm/versions/node/v18.20.4/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
gyp ERR! stack at async doWhich (/root/.nvm/versions/node/v18.20.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
gyp ERR! stack at async loadConfigGypi (/root/.nvm/versions/node/v18.20.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
gyp ERR! stack at async build (/root/.nvm/versions/node/v18.20.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
gyp ERR! stack at async run (/root/.nvm/versions/node/v18.20.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 4.4.0-19041-Microsoft
gyp ERR! command \"/root/.nvm/versions/node/v18.20.4/bin/node\" \"/root/.nvm/versions/node/v18.20.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba/build/Release/nodejieba.node\" \"--module_name=nodejieba\" \"--module_path=/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba/build/Release\" \"--napi_version=9\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v108\"
gyp ERR! cwd /home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba
gyp ERR! node -v v18.20.4
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v18.20.4/bin/node /root/.nvm/versions/node/v18.20.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba/build/Release/nodejieba.node --module_name=nodejieba --module_path=/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
node-pre-gyp ERR! System Linux 4.4.0-19041-Microsoft
node-pre-gyp ERR! command \"/root/.nvm/versions/node/v18.20.4/bin/node\" \"/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba
node-pre-gyp ERR! node -v v18.20.4
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok
Failed to execute '/root/.nvm/versions/node/v18.20.4/bin/node /root/.nvm/versions/node/v18.20.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/nodejieba/build/Release/nodejieba.node --module_name=nodejieba --module_path=/home/lisuccess Saved lockfile.
$ electron-builder install-app-deps
  • electron-builder  version=22.14.13
Done in 597.13s.
root@DESKTOP-LCLD13C:/home/liuqinyu/project/Stapxs-QQ-Lite-2.0# npm install -g node-pre-gyp
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated osenv@0.1.5: This package is no longer supported.
npm warn deprecated are-we-there-yet@1.1.7: This package is no longer supported.
npm warn deprecated npmlog@4.1.2: This package is no longer supported.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated gauge@2.7.4: This package is no longer supported.
npm warn deprecated node-pre-gyp@0.17.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

added 67 packages in 9s

3 packages are looking for funding
  run `npm fund` for details
root@DESKTOP-LCLD13C:/home/liuqinyu/project/Stapxs-QQ-Lite-2.0# yarn install
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps
  • electron-builder  version=22.14.13
Done in 2.08s.
root@DESKTOP-LCLD13C:/home/liuqinyu/project/Stapxs-QQ-Lite-2.0# electron-builder install-app-deps
electron-builder: command not found
root@DESKTOP-LCLD13C:/home/liuqinyu/project/Stapxs-QQ-Lite-2.0# yarn serve
yarn run v1.22.22
$ vue-cli-service serve
 INFO  Starting development server...
[24%] building (12/70 modules)
[BABEL] Note: The code generator has deoptimised the styling of /home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node[38%] building (233/469 modules)
[BABEL] Note: The code generator has deoptimised the styling of /home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node_modules/pinyin/esm/data/dict-zi.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node[51%] building (332/513 modules)
[BABEL] Note: The code generator has deoptimised the styling of /home/liuqinyu/project/Stapxs-QQ-Lite-2.0/node

 ERROR  Failed to compile with 1 error                                                              3:52:13 AM
 error  in ./src/pages/Chat.vue?vue&type=template&id=658eb408&scoped=true&ts=true

Module not found: Error: Can't resolve './../assets/img/qq-face/gif' in '/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/src/pages'

ERROR in ./src/pages/Chat.vue?vue&type=template&id=658eb408&scoped=true&ts=true (./node_modules/babel-loader/lib/index.js!./node_modules/@vue/cli-plugin-typescript/node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[4]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/Chat.vue?vue&type=template&id=658eb408&scoped=true&ts=true) 226:15-85
Module not found: Error: Can't resolve './../assets/img/qq-face/gif' in '/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/src/pages'
 @ ./src/pages/Chat.vue?vue&type=template&id=658eb408&scoped=true&ts=true 1:0-363 1:0-363
 @ ./src/pages/Chat.vue 1:0-85 8:68-74 18:84-20:3 19:29-35 18:2-20:4
 @ ./src/function/msg.ts 1450:49-75
 @ ./src/registerServiceWorker.ts 5:0-45
 @ ./src/main.ts 13:0-33

webpack compiled with 1 error
No issues found.


 WAIT  Compiling...                                                                                 3:52:14 AM

Compiling...


 ERROR  Failed to compile with 1 error                                                              3:52:15 AM

 error  in ./src/pages/Chat.vue?vue&type=template&id=658eb408&scoped=true&ts=true

Module not found: Error: Can't resolve './../assets/img/qq-face/gif' in '/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/src/pages'

ERROR in ./src/pages/Chat.vue?vue&type=template&id=658eb408&scoped=true&ts=true (./node_modules/babel-loader/lib/index.js!./node_modules/@vue/cli-plugin-typescript/node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[4]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/Chat.vue?vue&type=template&id=658eb408&scoped=true&ts=true) 226:15-85
Module not found: Error: Can't resolve './../assets/img/qq-face/gif' in '/home/liuqinyu/project/Stapxs-QQ-Lite-2.0/src/pages'
 @ ./src/pages/Chat.vue?vue&type=template&id=658eb408&scoped=true&ts=true 1:0-363 1:0-363
 @ ./src/pages/Chat.vue 1:0-85 8:68-74 18:84-20:3 19:29-35 18:2-20:4
 @ ./src/function/msg.ts 1450:49-75
 @ ./src/registerServiceWorker.ts 5:0-45
 @ ./src/main.ts 13:0-33

webpack compiled with 1 error
No issues found.
```

**Comment by Stapxs** [comment]
仓库有依赖子模块，clone 时记得带上 --recursive 或者 git submodule update --init 一下（

jieba 的报错是可忽略的，不影响

**Comment by Starry-Sky-World** [comment]
感谢指导，我试一下，后续继续反馈

**Comment by Starry-Sky-World** [comment]
感谢，成功啦！！！！！！！
