### ISSUE TITLE
[错误]群数量显示0，并且无法获取群组，收到@等消息也不会显示

### ISSUE THREAD

**Issue by mckuhei** [Stapxs/Stapxs-QQ-Lite-2.0#144]
### 错误来源

Stapxs QQ Lite（Web）

### 描述错误

群数量显示0，并且无法获取群组，收到@等消息也不会显示

### 复现流程
当返回的群名称为null时复现
使用的Lagrange.OneBot的版本: 0.0.3+5e7072c641d738749c016bd5d54a8af2761ce166

### 截图

![image](https://github.com/user-attachments/assets/270c64a4-a2ef-4874-9e9f-b382ca5f9c9c)
![image](https://github.com/user-attachments/assets/866af0fe-2f88-4589-a11e-30160f4b7291)
![image](https://github.com/user-attachments/assets/210732fb-7411-4153-a171-30c3949fffd9)
![image](https://github.com/user-attachments/assets/dd627819-cee7-49a8-be34-9342b1e6b53c)

### 版本信息

```
Debug Info - 2024/11/28 22:29:44
================================
System Info:
    OS Name          -> Windows 10
    Browser Name     -> chrome
    Browser Version  -> 130.0.0
Application Info:
    Uptime           -> 259.54 s
    Package Version  -> 3.0.0
    Service Work     -> undefined
Backend Info:
    Bot Info Name    -> Lagrange.OneBot
    Bot Info Version -> 0.0.3
    Loaded Config    -> Lagrange.OneBot
View Info:
    Doc Width        -> 1536 px
Network Info:
    Github           -> 806 ms
    Link API         -> failed
```

### 更多
```
处理消息或通知错误 - getGroupList：
 Error: argument should be string.
    at a (tiny-pinyin-moALDqOr.js:1:5640)
    at Object.convertToPinyin (tiny-pinyin-moALDqOr.js:1:5883)
    at main-DYb59qXu.js:5947:13965
    at Array.forEach (<anonymous>)
    at Ee (main-DYb59qXu.js:5947:13924)
    at Object.getGroupList (main-DYb59qXu.js:5947:5638)
    at Gt (main-DYb59qXu.js:5947:2618)
    at O.onmessage (main-DYb59qXu.js:5944:5232)
    at ns.onmessage (main-DYb59qXu.js:5944:4843)
```

**Comment by Stapxs** [comment]
> 当返回的群名称为null时复现

群名称为 null 疑似为 Lagrange 的 BUG，未复现成功 🤔

<img width="693" alt="image" src="https://github.com/user-attachments/assets/771132ff-f0c5-465c-8c82-bbe2275b8470" />

**Comment by mckuhei** [comment]
加个null检测吧，那个群名称为null的群在QQ9显示的是QQ群号

**Comment by mckuhei** [comment]
我之前一直在用你这个网页版QQ，后端一直都是Lagrange没更新，直到有天变成这样了，然后我尝试更新了Lagrange，没有解决，所以才来反馈的

**Comment by mckuhei** [comment]
说起来网页版一直在服务器上挂着没关过，不记得是什么时候开始的

**Comment by Stapxs** [comment]
> 说起来网页版一直在服务器上挂着没关过，不记得是什么时候开始的

网页就是个静态页面而已（x

**Comment by mckuhei** [comment]
这个群很久之前就是显示的QQ号了

**Comment by mckuhei** [comment]
![image](https://github.com/user-attachments/assets/abb09634-c16f-4087-b976-342a297c55d1)
现在啥都不显示了

**Comment by mckuhei** [comment]
2.8.0正常，那个名称为null的群在2.8.0显示空名称，手机QQ显示为群号
