### ISSUE TITLE
[错误]运行yarn start qq时报错

### ISSUE THREAD

**Issue by FengziLeo** [Stapxs/Stapxs-QQ-Lite-2.0#52]
**描述错误**

运行yarn start qq时报错，

node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\*\.oicq\*\password'
    at Object.openSync (node:fs:601:3)
    at Object.writeFileSync (node:fs:2249:35)
    at ReadStream.<anonymous> (C:\Users\*\Desktop\oicq-http2-main\bin\cli.js:115:9156)
    at Object.onceWrapper (node:events:628:26)
    at ReadStream.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TTY.onStreamRead (node:internal/stream_base_commons:190:23) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\*\\.oicq\\*\\password'
}

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

当手动建立目录后，报错
node:internal/fs/utils:347
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, open 'C:\Users\*\.oicq\*\password'
    at Object.openSync (node:fs:601:3)
    at Object.writeFileSync (node:fs:2249:35)
    at ReadStream.<anonymous> (C:\Users\*\Desktop\oicq-http2-main\bin\cli.js:115:9156)
    at Object.onceWrapper (node:events:628:26)
    at ReadStream.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TTY.onStreamRead (node:internal/stream_base_commons:190:23) {
  errno: -4068,
  syscall: 'open',
  code: 'EISDIR',
  path: 'C:\\Users\\*\\.oicq\\*\\password'
}

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**复现流程**

**截图**

**版本信息**

1 - 2.4.3
2 - production
3 - .
4 - chrome
5 - 104.0.5112
6 - Windows 10
7 - undefined
8 - undefined
9 - 1184 px
10 - 20.3.12
11 - C:\Users\*
**更多**

**Comment by Stapxs** [comment]
emmm 看下目录结构
或是干脆只保留 config.js(config.json) 把其他的都删了试试 XD

**Comment by FengziLeo** [comment]
> 
我把C:\Users\丰子磊\.oicq下除了config.json删除后，再次运行yurn start qq还是会报错
完整内容如下图
`C:\Users\丰子磊\Desktop\oicq-http2-main>yarn start 1257814423
yarn run v1.22.19
$ npm run prepare && node bin/oicq-http2.js 1257814423

> oicq-http2@1.1.0 prepare
> esbuild src/main.ts --outfile=bin/cli.js --bundle --minify-syntax --minify-whitespace --platform=node --log-level=warning

[2023-04-23T11:08:16.544] [MARK] [icqq] - 创建了新的设备文件：C:\Users\丰子磊\.oicq\device.json
[2023-04-23T11:08:16.548] [MARK] [icqq] - ----------
[2023-04-23T11:08:16.548] [MARK] [icqq] - Package Version: icqq@0.0.31 (Released on 2023/3/13)
[2023-04-23T11:08:16.548] [MARK] [icqq] - View Changelogs：https://github.com/icqqjs/icqq/releases
[2023-04-23T11:08:16.548] [MARK] [icqq] - ----------
[2023-04-23T11:08:16.564] [INFO] [icqq] - 开启http服务器成功 正在监听0.0.0.0:5700
请输入密码 (直接按回车扫码登录):

node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\丰子磊\.oicq\1257814423\password'
    at Object.openSync (node:fs:601:3)
    at Object.writeFileSync (node:fs:2249:35)
    at ReadStream.<anonymous> (C:\Users\丰子磊\Desktop\oicq-http2-main\bin\cli.js:115:9156)
    at Object.onceWrapper (node:events:628:26)
    at ReadStream.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TTY.onStreamRead (node:internal/stream_base_commons:190:23) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\丰子磊\\.oicq\\1257814423\\password'
}

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

我尝试将文件夹对于everyone的权限赋予全部权限，但是还是不行o(╥﹏╥)o

**Comment by Stapxs** [comment]
passowrd 是缓存的密码才是 emmm 试试扫码登陆？没遇到过 XD

**Comment by FengziLeo** [comment]
更悲伤的是，以上报错就是扫码登录（直接回车）出现的

**Comment by Stapxs** [comment]
> 更悲伤的是，以上报错就是扫码登录（直接回车）出现的

那就试试密码登录（抱头

**Comment by FengziLeo** [comment]
> > 更悲伤的是，以上报错就是扫码登录（直接回车）出现的
> 
> 那就试试密码登录（抱头

也不行   : (

**Comment by Stapxs** [comment]
emmmm 不太清楚了 XD
可以考虑去隔壁 oicq 问问 （ https://github.com/takayama-lily/oicq/issues ）

**Comment by FengziLeo** [comment]
> emmmm 不太清楚了 XD 可以考虑去隔壁 oicq 问问 （ https://github.com/takayama-lily/oicq/issues ）

好的嘞，那我去问问他们

**Comment by Stapxs** [comment]
> > emmmm 不太清楚了 XD 可以考虑去隔壁 oicq 问问 （ https://github.com/takayama-lily/oicq/issues ）
> 
> 好的嘞，那我去问问他们

欸等会儿 emmm 你试试手动创建一个叫 password 的文件进 .oicq/<qq> 下面去试试 emmm

**Comment by FengziLeo** [comment]
> > > emmmm 不太清楚了 XD 可以考虑去隔壁 oicq 问问 （ https://github.com/takayama-lily/oicq/issues ）
> > 
> > 
> > 好的嘞，那我去问问他们
> 
> 欸等会儿 emmm 你试试手动创建一个叫 password 的文件进 .oicq/ 下面去试试 emmm

是在这个路径吗？C:\Users\丰子磊\.oicq\password
依然报错node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\丰子磊\.oicq\1257814423\password'

创建C:\Users\丰子磊\.oicq\1257814423\password后提示
node:internal/fs/utils:347
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, open 'C:\Users\丰子磊\.oicq\1257814423\password'

我去试了一下https://github.com/takayama-lily/oicq-template这个，发现可以正常出现扫码登录的页面

**Comment by Stapxs** [comment]
> > > > emmmm 不太清楚了 XD 可以考虑去隔壁 oicq 问问 （ https://github.com/takayama-lily/oicq/issues ）
> > > 
> > > 
> > > 好的嘞，那我去问问他们
> > 
> > 
> > 欸等会儿 emmm 你试试手动创建一个叫 password 的文件进 .oicq/ 下面去试试 emmm
> 
> 是在这个路径吗？C:\Users\丰子磊.oicq\password 依然报错node:internal/fs/utils:347 throw err; ^
> 
> Error: ENOENT: no such file or directory, open 'C:\Users\丰子磊.oicq\1257814423\password'
> 
> 创建C:\Users\丰子磊.oicq\1257814423\password后提示 node:internal/fs/utils:347 throw err; ^
> 
> Error: EISDIR: illegal operation on a directory, open 'C:\Users\丰子磊.oicq\1257814423\password'
> 
> 我去试了一下[https://github.com/takayama-lily/oicq-template这个，发现可以正常出现扫码登录的页面](https://github.com/takayama-lily/oicq-template%E8%BF%99%E4%B8%AA%EF%BC%8C%E5%8F%91%E7%8E%B0%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E5%87%BA%E7%8E%B0%E6%89%AB%E7%A0%81%E7%99%BB%E5%BD%95%E7%9A%84%E9%A1%B5%E9%9D%A2)

创建的是文件吧，password 是个没有文件后缀的文件不是文件夹 emmm
如果是的话那我真不清楚发生了啥了 XD

**Comment by FengziLeo** [comment]
> 

哦吼，这下可以了，正常出现二维码了，感谢！Thanks♪(･ω･)ﾉ

**Comment by Stapxs** [comment]
好耶
